import Image from "next/image";
import { content, navigation, PHONE, WHATSAPP_URL } from "@/lib/content";
import { getSiteUrl } from "@/lib/site";
import { Icon, WhatsAppIcon } from "@/components/icons";
import { FloatingWhatsApp, Logo, SectionLabel, WhatsAppCTA } from "@/components/ui";
import { MobileNav } from "@/components/mobile-nav";
import { RevealObserver } from "@/components/reveal";
import { AdminMockup, OrderingMockup } from "@/components/mockups";

export default function Home() {
  const siteUrl = getSiteUrl();
  const organization = { "@context": "https://schema.org", "@type": "Organization", name: "VENTA TOUCH", description: "Soluciones integrales de autoservicio y puntos de venta mediante tótems y kioscos interactivos.", telephone: PHONE, ...(siteUrl ? { url: siteUrl.href, logo: new URL("/images/logo-dark.webp", siteUrl).href } : {}), contactPoint: { "@type": "ContactPoint", telephone: PHONE, contactType: "sales", availableLanguage: "Spanish" } };

  return <>
    <a href="#contenido" className="skip-link">Saltar al contenido</a>
    <header className="site-header"><div className="container header-inner"><Logo/><nav className="desktop-nav" aria-label="Navegación principal">{navigation.map(link => <a href={link.href} key={link.href}>{link.label}</a>)}</nav><WhatsAppCTA variant="outline" className="header-cta" location="header">Cotizar mi solución</WhatsAppCTA><MobileNav/></div></header>
    <main id="contenido">
      <section className="hero" id="inicio" aria-labelledby="hero-title">
        <div className="container hero-grid">
          <div className="hero-copy"><SectionLabel>{content.hero.eyebrow}</SectionLabel><h1 id="hero-title">TU PRÓXIMO<br/>PUNTO DE VENTA<br/>ES <span>TOUCH.</span><span className="title-square" aria-hidden="true"/></h1><p className="hero-description">{content.hero.description}</p><div className="hero-actions"><WhatsAppCTA location="hero">{content.hero.cta}</WhatsAppCTA><a className="text-link" href="#solucion">Conocer la solución <Icon name="down" size={16}/></a></div><p className="hero-note"><Icon name="check" size={14}/>Una solución completa. Un solo equipo a tu lado.</p></div>
          <figure className="hero-visual"><div className="hero-orbit" aria-hidden="true"/><span className="visual-index" aria-hidden="true">VT / AUTOSERVICIO</span><Image src="/images/kiosk-hero.webp" alt="Render conceptual de un tótem VENTA TOUCH con menú táctil, terminal de pago e impresora de tickets" width={1122} height={1402} sizes="(max-width: 767px) 100vw, (max-width: 1100px) 50vw, 620px" loading="eager" fetchPriority="high" className="hero-kiosk"/></figure>
        </div>
        <div className="hero-bottom container"><span>EL FUTURO DE TU MOSTRADOR, HOY.</span><a href="#solucion" aria-label="Explorar la solución"><Icon name="down" size={18}/></a><span>DISEÑADO PARA TU FORMA DE VENDER</span></div>
      </section>

      <div className="capabilities-strip"><div className="container capabilities-inner">{[{ icon: "monitor", text: "Hardware + software" }, { icon: "card", text: "Pagos integrados" }, { icon: "printer", text: "Tickets y comandas" }, { icon: "support", text: "Instalación y soporte" }].map(item => <span key={item.text}><Icon name={item.icon} size={21}/>{item.text}</span>)}</div></div>

      <section className="section solution-section" id="solucion" aria-labelledby="solution-title"><div className="container"><div className="section-heading" data-reveal><div><SectionLabel>UNA SOLUCIÓN. TODO RESUELTO.</SectionLabel><h2 id="solution-title">MUCHO MÁS<br/>QUE UN <span>TÓTEM.</span></h2></div><p>El equipo, el sistema y las personas que lo hacen funcionar. Integramos cada parte para que vos puedas enfocarte en tu negocio.</p></div><div className="solution-grid">{content.solution.map(item => <article className="solution-item" key={item.number} data-reveal><div className="solution-item-top"><Icon name={item.icon} size={32}/><span>{item.number}</span></div><h3>{item.title}</h3><p>{item.description}</p><ul>{item.items.map(text => <li key={text}><Icon name="check" size={15}/>{text}</li>)}</ul></article>)}</div></div></section>

      <section className="section experience-section" id="como-funciona" aria-labelledby="experience-title"><div className="container experience-grid"><div className="experience-visual" data-reveal><OrderingMockup/></div><div className="experience-copy" data-reveal><SectionLabel>SIMPLE PARA TU CLIENTE</SectionLabel><h2 id="experience-title">UNOS TOQUES.<br/>UN MEJOR<br/><span>PUNTO DE VENTA.</span></h2><p className="section-intro">Una experiencia guiada, desde la primera elección hasta el último paso del pedido.</p><ol className="customer-steps">{content.steps.map((step, index) => <li key={step.title}><span className="step-number">0{index + 1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol><a className="text-link orange-link" href="#implementacion">Así lo llevamos a tu local <Icon name="diagonal" size={18}/></a></div></div><div className="container benefits-grid">{content.benefits.map(item => <article key={item.title} data-reveal><Icon name={item.icon} size={24}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>

      <section className="section admin-section" aria-labelledby="admin-title"><div className="container admin-grid"><div data-reveal><SectionLabel>SIMPLE PARA VOS</SectionLabel><h2 id="admin-title">TU NEGOCIO.<br/><span>BAJO CONTROL.</span></h2><p className="section-intro">El autoservicio de tu local, conectado a un panel administrativo web.</p><p className="body-muted">Centralizá la gestión de tu punto de venta desde una misma herramienta. Definimos la configuración según tu operación y te acompañamos desde el inicio.</p><div className="admin-feature"><Icon name="layers" size={20}/><span>Administración en un mismo lugar</span></div><div className="admin-feature"><Icon name="support" size={20}/><span>Configuración y acompañamiento técnico</span></div><WhatsAppCTA variant="outline" location="admin">Consultar por el software</WhatsAppCTA></div><div data-reveal><AdminMockup/></div></div></section>

      <section className="section industries-section" id="aplicaciones" aria-labelledby="industries-title"><div className="container"><div className="section-heading" data-reveal><div><SectionLabel>CADA NEGOCIO TIENE SU TOUCH</SectionLabel><h2 id="industries-title">DONDE HAY UN CLIENTE,<br/>HAY UNA <span>OPORTUNIDAD.</span></h2></div><p>Tu forma de trabajar es el punto de partida. Encontramos juntos dónde el autoservicio puede hacer la diferencia.</p></div><div className="industries-grid"><figure className="restaurant-figure" data-reveal><Image src="/images/restaurant.webp" alt="Escena conceptual de un tótem de autoservicio en una cafetería y restaurante" width={1536} height={1024} sizes="(max-width: 767px) 100vw, 55vw"/><div className="restaurant-caption"><span>MENOS PASOS. MÁS EXPERIENCIA.</span><p>Tu local, un paso adelante.</p></div><figcaption>Escena ilustrativa</figcaption></figure><div className="industry-list">{content.industries.map((item, index) => <article key={item.title} data-reveal><div className="industry-title"><Icon name={item.icon} size={23}/><span>0{index + 1}</span></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></div></section>

      <section className="section implementation-section" id="implementacion" aria-labelledby="implementation-title"><div className="container"><div className="section-heading" data-reveal><div><SectionLabel>DE LA IDEA A TU LOCAL</SectionLabel><h2 id="implementation-title">VOS TRAÉS EL NEGOCIO.<br/>NOSOTROS, <span>LA SOLUCIÓN.</span></h2></div><p>Te acompañamos en cada etapa para que incorporar autoservicio tenga un camino claro.</p></div><ol className="implementation-grid">{content.implementation.map((step, index) => <li key={step.title} data-reveal><div className="implementation-number"><span>0{index + 1}</span><Icon name="arrow" size={22}/></div><h3>{step.title}</h3><p>{step.text}</p></li>)}</ol><div className="implementation-note"><Icon name="shield" size={21}/><p>Una propuesta a medida. Desde el primer contacto hasta la puesta en marcha.</p></div></div></section>

      <section className="section faq-section" id="preguntas" aria-labelledby="faq-title"><div className="container faq-grid"><div data-reveal><SectionLabel>HABLEMOS CLARO</SectionLabel><h2 id="faq-title">BUENAS PREGUNTAS.<br/><span>RESPUESTAS CLARAS.</span></h2><p className="section-intro">Cada proyecto es distinto.<br/>Estamos para ayudarte a definir el tuyo.</p><WhatsAppCTA variant="outline" location="faq">Resolver mis dudas</WhatsAppCTA></div><div className="faq-list" data-reveal>{content.faq.map((item, index) => <details key={item.question} name="faq"><summary><span className="faq-number">0{index + 1}</span><span>{item.question}</span><Icon name="plus" size={19}/></summary><div className="faq-answer"><p>{item.answer}</p></div></details>)}</div></div></section>

      <section className="contact-section" id="contacto" aria-labelledby="contact-title"><div className="container contact-inner" data-reveal><div className="contact-copy"><SectionLabel light>EL PRÓXIMO PASO EMPIEZA CON UNA CHARLA</SectionLabel><h2 id="contact-title">DALE UN NUEVO<br/><span>TOUCH A TU NEGOCIO.</span></h2><p>Contanos cómo funciona tu negocio.<br/>Te ayudamos a dar el próximo paso.</p><WhatsAppCTA variant="dark" location="closing">Consultar mi proyecto por WhatsApp</WhatsAppCTA><p className="contact-helper">Contanos tu rubro, ubicación y qué te gustaría automatizar.</p></div><div className="contact-art" aria-hidden="true"><span>TOUCH</span><div><Icon name="diagonal" size={128}/></div></div></div></section>
    </main>
    <footer className="site-footer"><div className="container"><div className="footer-top"><div><Logo footer/><p>Tecnología que conecta.<br/>Soluciones que hacen crecer tu negocio.</p></div><div className="footer-contact"><span>HABLEMOS DE TU PROYECTO</span><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" data-cta="footer"><WhatsAppIcon size={22}/>{PHONE}<Icon name="diagonal" size={18}/></a></div></div><div className="footer-bottom"><p>© {new Date().getFullYear()} VENTA TOUCH. Todos los derechos reservados.</p><a href="#inicio">Volver arriba <Icon name="diagonal" size={15}/></a></div></div></footer>
    <FloatingWhatsApp/><RevealObserver/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organization).replace(/</g, "\\u003c") }}/>
  </>;
}
